### ISSUE TITLE
User registration

### ISSUE THREAD

**Issue by Ihor-BA** [ita-social-projects/Home-UI#22]
**Description**
As a User I want to register in cooperation system so I can use the system.

**Preconditions:**
Сo-owners of apartment building association shall be created in system.
Cooperation admin should send invitation e-mail with redirection link and register key due to user role.

**Acceptance criteria**

1. E-mail with redirection link shall redirect user to registration page.
2. When e-mail is already register in the system - system shall propose user to login.
3. When redirection link is clicked user redirect to the registration page with requires to input fields: First name, Middle name, Last name, e-mail, password, confirm password, registration key.
4. When all form fields filled in correctly button “Register” becomes available.
5. User can login system with e-mail and password with rights due to his role.

**Fields fulfill requirements**
Email address field: Max email length – 320 symbols, Min email length - 5 symbols, Recipient name shall consist of uppercase and lowercase letters in English (A-Z, a-z), digits from 0 to 9, special characters ! # $ % & ' * + - / = ? ^ _ ` { | ( ) , : ; < > @ [ \ ]
A special character cannot appear as the first or last character in an email address or appear consecutively two or more times.
Presence of one @ symbol is obligatory. Domain name shall consist of uppercase and lowercase letters in English (A-Z, a-z), digits from 0 to 9, hyphen (-), a period (.)
The address has to have a period (.) symbol placed after the domain name before the top top-level domain in an email address.

First name, Middle name, Last name: Max  length – 50 symbols. Min length - 1 symbol. Symbols are uppercase and lowercase letters (A-Z, a-z). Special characters ! # $ % & ' * + - / = ? ^ _ ` { | ( ) , : ; < > @ [ \ ]

Password:  
Max  length – 128 symbols
Min length - 8 symbol
Symbols are uppercase and lowercase letters in English (A-Z, a-z), digits from 0 to 9

Password confirm: fields password and confirm password has to contain the same value. 

Registration key (token): Length – 36 symbols. Symbols are uppercase and lowercase letters in English (A-Z, a-z), digits from 0 to 9

[https://home-project-engineering.atlassian.net/browse/HP-13](url)

![Flow_registerUser](https://user-images.githubusercontent.com/62280063/132638517-365e7f72-a10b-40a9-bb1e-a79a89484ea1.jpeg)

**Comment by maveric-ui** [comment]
FE: 42

**Comment by what-the-hub** [comment]
@Ihor-BA hello! I have one question.  Do we really need to be able to write special characters in First name, Middle name, Last name form?

**Comment by Ihor-BA** [comment]
@what-the-hub 

Yes, I`m sure we need left it because lots of people with Ukrainian and not only name still use it. Also in our country we have a lot of different nationalities uses middle name`s with special characters like: M`aryam Masud-Surah al Shams; Carl Eernest-Maria Friedrich; Матр'юсевич-Геращенко and other.

**Comment by what-the-hub** [comment]
the task was completed in 54 cause i had problems with vuex and validation

**Comment by maveric-ui** [comment]
27.09.2021: 18 / 24 / 30

**Comment by what-the-hub** [comment]
There is one question. In our task there is an input with validation for the token which we copy from the letter. We also talked about the future autocomplete of this token when clicking on the link in email.
At this stage we having received the token, the validation prepared by the task does not pass it, because the token looks like: **a1a1a111-11a1-11aa-a11a-11aaaa1aa111**.
As you can see, it contains dashes that the validation does not skip.
We having discussed this issue, there is a proposal at this stage to remove the validation at the token input, since:

-  there should be a prefil in the future
-  if you copy-paste the token, then everything should be inserted correctly
-  I suppose that some parameters of the token may change (the length or position of the dash)
-  we can leave only **required** validation for this field

@Ihor-BA 
What do you think about this?

**Comment by Ihor-BA** [comment]
@what-the-hub  It can be in the next way:

**Acceptance criteria for fulfillment of the ''Registration key'' field:** 
- Fulfill of the ''Registration key'' field is obligatory
- Registration key (token) shall be copy-pasted by User from the invitation e-mail.
